"""Initial schema

Revision ID: 7fe6706b9b5d
Revises: 
Create Date: 2026-04-10 12:17:30.183908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7fe6706b9b5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('orphan_magics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('magic_number', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orphan_magics_account_id'), 'orphan_magics', ['account_id'], unique=False)
    op.create_index(op.f('ix_orphan_magics_id'), 'orphan_magics', ['id'], unique=False)
    op.create_index(op.f('ix_orphan_magics_magic_number'), 'orphan_magics', ['magic_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trading_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('api_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_accounts_api_token'), 'trading_accounts', ['api_token'], unique=True)
    op.create_index(op.f('ix_trading_accounts_user_id'), 'trading_accounts', ['user_id'], unique=False)
    op.create_table('user_alert_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('metric_key', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('custom_theme_json', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_sync_token', sa.String(length=36), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('colors', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trading_account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy_ids', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('auto_include_new', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('gauss_params', sa.JSON(), nullable=True),
    sa.Column('distribution_fit', sa.JSON(), nullable=True),
    sa.Column('risk_config', sa.JSON(), nullable=True),
    sa.Column('max_drawdown_limit', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit', sa.Float(), nullable=False),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_trading_account_id'), 'portfolios', ['trading_account_id'], unique=False)
    op.create_table('real_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trading_account_id', sa.String(length=36), nullable=False),
    sa.Column('ticket', sa.Integer(), nullable=False),
    sa.Column('magic_number', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('deal_type', sa.String(length=10), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_trades_magic_number'), 'real_trades', ['magic_number'], unique=False)
    op.create_index(op.f('ix_real_trades_ticket'), 'real_trades', ['ticket'], unique=False)
    op.create_index(op.f('ix_real_trades_trading_account_id'), 'real_trades', ['trading_account_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trading_account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('magic_number', sa.Integer(), nullable=False),
    sa.Column('magic_aliases', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('max_drawdown_limit', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit', sa.Float(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('gauss_params', sa.JSON(), nullable=True),
    sa.Column('distribution_fit', sa.JSON(), nullable=True),
    sa.Column('risk_config', sa.JSON(), nullable=True),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('bt_discount', sa.Float(), nullable=False),
    sa.Column('risk_multiplier', sa.Float(), nullable=False),
    sa.Column('original_equity_curve', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_trading_account_id'), 'strategies', ['trading_account_id'], unique=False)
    op.create_table('user_alert_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_at_trigger', sa.Float(), nullable=False),
    sa.Column('message_sent', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['user_alert_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alert_history')
    op.drop_index(op.f('ix_strategies_trading_account_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_real_trades_trading_account_id'), table_name='real_trades')
    op.drop_index(op.f('ix_real_trades_ticket'), table_name='real_trades')
    op.drop_index(op.f('ix_real_trades_magic_number'), table_name='real_trades')
    op.drop_table('real_trades')
    op.drop_index(op.f('ix_portfolios_trading_account_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('user_themes')
    op.drop_table('user_preferences')
    op.drop_table('user_alert_configs')
    op.drop_index(op.f('ix_trading_accounts_user_id'), table_name='trading_accounts')
    op.drop_index(op.f('ix_trading_accounts_api_token'), table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orphan_magics_magic_number'), table_name='orphan_magics')
    op.drop_index(op.f('ix_orphan_magics_id'), table_name='orphan_magics')
    op.drop_index(op.f('ix_orphan_magics_account_id'), table_name='orphan_magics')
    op.drop_table('orphan_magics')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
