"""add briefing_hour_utc and last_briefing_date to user_preferences

Revision ID: e74db5cda078
Revises: 8b58e34200b4
Create Date: 2026-04-25 09:22:05.682349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74db5cda078'
down_revision: Union[str, Sequence[str], None] = '8b58e34200b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
